target("CampaignRuntime")
    set_kind("static")
    set_group("common")
    add_includedirs(".", {public = true})
    add_headerfiles("**.h")
    add_files("**.cpp")
    add_deps("CampaignPersistence", {public = true})
